"""
C Handler for ESP-IDF TDD with Unity + CMock.
Generates ESP-IDF compatible C code with real ESP-IDF APIs.
"""
import subprocess
import re
from pathlib import Path
from typing import Dict, Any, List, Optional
from handlers.base_handler import BaseHandler, TestResult, CodeFile

class CHandler(BaseHandler):
    """Handler for ESP-IDF C code with ESP-IDF toolchain"""
    
    @property
    def language_name(self) -> str:
        return "C (ESP-IDF)"
    
    @property
    def file_extensions(self) -> List[str]:
        return ['.c', '.h']
    
    @property
    def test_framework(self) -> str:
        return "ESP-IDF Unity + CMock"
    
    def setup_environment(self) -> bool:
        """Check for ESP-IDF or gcc fallback."""
        idf_path = Path('/opt/esp-idf')
        if idf_path.exists():
            print(f"[C_HANDLER] ESP-IDF found at {idf_path}")
            try:
                result = subprocess.run(['idf.py', '--version'], capture_output=True, text=True, timeout=10)
                if result.returncode == 0:
                    print(f"[C_HANDLER] ESP-IDF: {result.stdout.split(chr(10))[0]}")
                    return True
            except Exception as e:
                print(f"[C_HANDLER] ESP-IDF check warning: {e}")
        
        # Fallback to gcc
        try:
            result = subprocess.run(['gcc', '--version'], capture_output=True, text=True, timeout=10)
            if result.returncode == 0:
                print(f"[C_HANDLER] Using gcc fallback: {result.stdout.split(chr(10))[0]}")
                return True
        except Exception as e:
            print(f"[C_HANDLER] No compiler found: {e}")
            return False
        return False
    
    def generate_tests(self, spec: Dict[str, Any], code_files: List[CodeFile], failures: List[str] = None) -> List[CodeFile]:
        """Generate ESP-IDF Unity test files."""
        test_files = []
        
        module_name = spec.get('module_name', 'generated')
        raw_content = spec.get('raw', '')
        
        # Detect CAN/TWAI from spec
        is_can = 'can' in raw_content.lower() or 'twai' in raw_content.lower()
        is_ble = 'ble' in raw_content.lower() or 'bluetooth' in raw_content.lower()
        is_motor = 'motor' in raw_content.lower() or 'odrive' in raw_content.lower()
        
        # Generate ESP-IDF component test file
        test_content = f'''/*
 * ESP-IDF Test file for {module_name}
 * Generated by TDD Agent
 * Run with: idf.py build-test
 */
#include <stdio.h>
#include <unity.h>
#include "esp_log.h"

/* Mock ESP-IDF components for host testing */
#ifdef CONFIG_IDF_TARGET_HOST
/* Host test mode - use mocks */
#include "unity_test_utils.h"

static const char *TAG = "{module_name}_test";

void setUp(void) {{
    /* Setup before each test */
    ESP_LOGI(TAG, "Test setup");
}}

void tearDown(void) {{
    /* Cleanup after each test */
    ESP_LOGI(TAG, "Test teardown");
}}

/* Test cases */
void test_{module_name}_initialization(void) {{
    ESP_LOGI(TAG, "Testing initialization");
    /* Test happy path initialization */
    TEST_ASSERT_TRUE(1);
}}

void test_{module_name}_error_handling(void) {{
    ESP_LOGI(TAG, "Testing error handling");
    /* Test error conditions */
    TEST_ASSERT_TRUE(1);
}}

void test_{module_name}_edge_cases(void) {{
    ESP_LOGI(TAG, "Testing edge cases");
    /* Test boundary conditions */
    TEST_ASSERT_TRUE(1);
}}

void app_main(void) {{
    ESP_LOGI(TAG, "Starting {module_name} tests");
    
    UNITY_BEGIN();
    
    RUN_TEST(test_{module_name}_initialization);
    RUN_TEST(test_{module_name}_error_handling);
    RUN_TEST(test_{module_name}_edge_cases);
    
    UNITY_END();
}}

#else
/* Device mode - placeholder for actual ESP32 tests */
void app_main(void) {{
    printf("{module_name} tests running on ESP32\\n");
}}
#endif
'''
        # Write test file
        test_dir = self.workspace / 'test'
        test_dir.mkdir(parents=True, exist_ok=True)
        test_path = test_dir / f'test_{module_name}.c'
        test_files.append(CodeFile(path=str(test_path), content=test_content, language='c'))
        
        return test_files
    
    def generate_code(self, spec: Dict[str, Any], test_files: List[CodeFile]) -> List[CodeFile]:
        """Generate ESP-IDF compatible C code."""
        code_files = []
        
        module_name = spec.get('module_name', 'generated')
        raw_content = spec.get('raw', '')
        
        # Detect requirements from spec
        is_can = 'can' in raw_content.lower() or 'twai' in raw_content.lower()
        is_ble = 'ble' in raw_content.lower() or 'bluetooth' in raw_content.lower()
        is_motor = 'motor' in raw_content.lower() or 'odrive' in raw_content.lower()
        is_display = 'lvgl' in raw_content.lower() or 'display' in raw_content.lower()
        
        # Generate header file
        header_content = f'''/*
 * {module_name} header
 * ESP-IDF Compatible
 * Generated by TDD Agent
 */
#ifndef {module_name.upper().replace("-", "_")}_H
#define {module_name.upper().replace("-", "_")}_H

#include <stdint.h>
#include <stdbool.h>
#include "esp_err.h"

#ifdef __cplusplus
extern "C" {{
#endif

/* Module initialization */
esp_err_t {module_name}_init(void);

/* Module cleanup */
void {module_name}_cleanup(void);

/* Module status check */
bool {module_name}_is_initialized(void);

'''

        # Add module-specific functions based on detected requirements
        if is_can:
            header_content += f'''/* CAN Bus Functions */
typedef struct {{
    uint32_t id;
    uint8_t data[8];
    uint8_t len;
}} can_frame_t;

esp_err_t {module_name}_send_frame(can_frame_t *frame);
esp_err_t {module_name}_receive_frame(can_frame_t *frame, uint32_t timeout_ms);
esp_err_t {module_name}_set_baudrate(uint32_t baudrate);

'''
        
        if is_ble:
            header_content += f'''/* BLE Functions */
esp_err_t {module_name}_ble_init(void);
esp_err_t {module_name}_ble_connect(uint8_t *mac_addr);
esp_err_t {module_name}_ble_send(uint8_t *data, size_t len);
esp_err_t {module_name}_ble_disconnect(void);

'''
        
        if is_motor:
            header_content += f'''/* Motor Control Functions */
typedef enum {{
    MOTOR_STATE_DISABLED,
    MOTOR_STATE_READY,
    MOTOR_STATE_ENABLED,
    MOTOR_STATE_FAULT
}} motor_state_t;

typedef enum {{
    MOTOR_MODE_TORQUE,
    MOTOR_MODE_VELOCITY,
    MOTOR_MODE_POSITION
}} motor_mode_t;

esp_err_t {module_name}_set_mode(motor_mode_t mode);
esp_err_t {module_name}_set_torque(float torque);
esp_err_t {module_name}_set_velocity(float velocity);
esp_err_t {module_name}_set_position(float position);
motor_state_t {module_name}_get_state(void);

'''
        
        if is_display:
            header_content += f'''/* Display Functions */
esp_err_t {module_name}_display_init(void);
esp_err_t {module_name}_display_clear(void);
esp_err_t {module_name}_display_text(const char *text, int x, int y);
esp_err_t {module_name}_display_update(void);

'''
        
        # Close header
        header_content += '''
#ifdef __cplusplus
}}
#endif

#endif /* ''' + f'''{module_name.upper().replace("-", "_")}_H''' + ''' */
'''
        
        # Generate source file
        source_content = f'''/*
 * {module_name} implementation
 * ESP-IDF Compatible
 * Generated by TDD Agent
 */
#include "{module_name}.h"
#include "esp_log.h"
#include "esp_timer.h"

#ifdef CONFIG_IDF_TARGET_HOST
/* Host test mode mocks */
#include <string.h>
#else
/* ESP32 device mode */
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#endif

static const char *TAG = "{module_name}";

/* Internal state */
static bool s_initialized = false;

'''

        # Add module-specific implementation
        if is_can:
            source_content += f'''/* CAN Bus Implementation */
#include "driver/twai.h"

static twai_driver_config_t s_twai_config = {{
    .tx_io = CONFIG_TWAI_TX_GPIO,
    .rx_io = CONFIG_TWAI_RX_GPIO,
    .clkout_io = TWAI_IO_UNUSED,
    .bus_off_io = TWAI_IO_UNUSED,
    .tx_queue_len = 16,
    .rx_queue_len = 16,
    .alerts_enabled = TWAI_ALERT_NONE,
    .rx_mode = TWAI_NORMAL_MODE,
    .tx_mode = TWAI_NORMAL_MODE,
}};

esp_err_t {module_name}_init(void) {{
    if (s_initialized) {{
        ESP_LOGW(TAG, "Already initialized");
        return ESP_OK;
    }}
    
    ESP_LOGI(TAG, "Initializing {module_name}");
    
    /* Install TWAI driver */
    esp_err_t err = twai_driver_install(&s_twai_config, NULL, NULL);
    if (err != ESP_OK) {{
        ESP_LOGE(TAG, "TWAI driver install failed: %s", esp_err_to_name(err));
        return err;
    }}
    
    /* Start TWAI controller */
    err = twai_start();
    if (err != ESP_OK) {{
        ESP_LOGE(TAG, "TWAI start failed: %s", esp_err_to_name(err));
        return err;
    }}
    
    s_initialized = true;
    ESP_LOGI(TAG, "{module_name} initialized successfully");
    return ESP_OK;
}}

esp_err_t {module_name}_send_frame(can_frame_t *frame) {{
    if (!s_initialized) {{
        ESP_LOGE(TAG, "Not initialized");
        return ESP_ERR_INVALID_STATE;
    }}
    
    twai_message_t msg = {{
        .identifier = frame->id,
        .data_length_code = frame->len,
        .ss = 0,
        .rtr = 0,
        .extd = 0,
    }};
    memcpy(msg.data, frame->data, frame->len);
    
    esp_err_t err = twai_transmit(&msg, pdMS_TO_TICKS(100));
    if (err != ESP_OK) {{
        ESP_LOGE(TAG, "TX failed: %s", esp_err_to_name(err));
        return err;
    }}
    
    return ESP_OK;
}}

esp_err_t {module_name}_receive_frame(can_frame_t *frame, uint32_t timeout_ms) {{
    if (!s_initialized) {{
        return ESP_ERR_INVALID_STATE;
    }}
    
    twai_message_t msg;
    esp_err_t err = twai_receive(&msg, pdMS_TO_TICKS(timeout_ms));
    if (err != ESP_OK) {{
        return err;
    }}
    
    frame->id = msg.identifier;
    frame->len = msg.data_length_code;
    memcpy(frame->data, msg.data, frame->len);
    
    return ESP_OK;
}}

esp_err_t {module_name}_set_baudrate(uint32_t baudrate) {{
    /* TWAI timing configuration would go here */
    ESP_LOGI(TAG, "Setting baudrate to %lu", baudrate);
    return ESP_OK;
}}

void {module_name}_cleanup(void) {{
    if (!s_initialized) {{
        return;
    }}
    
    ESP_LOGI(TAG, "Cleaning up {module_name}");
    twai_driver_uninstall();
    s_initialized = false;
}}

'''
        
        # Add BLE implementation
        if is_ble:
            source_content += f'''/* BLE Implementation */
#include "nimble/nimble_port.h"

esp_err_t {module_name}_ble_init(void) {{
    ESP_LOGI(TAG, "Initializing BLE");
    /* BLE initialization would go here */
    return ESP_OK;
}}

esp_err_t {module_name}_ble_connect(uint8_t *mac_addr) {{
    ESP_LOGI(TAG, "Connecting to BLE device");
    return ESP_OK;
}}

esp_err_t {module_name}_ble_send(uint8_t *data, size_t len) {{
    return ESP_OK;
}}

esp_err_t {module_name}_ble_disconnect(void) {{
    return ESP_OK;
}}

'''
        
        # Add motor control implementation
        if is_motor:
            source_content += f'''/* Motor Control Implementation */
static motor_state_t s_motor_state = MOTOR_STATE_DISABLED;
static motor_mode_t s_motor_mode = MOTOR_MODE_TORQUE;

esp_err_t {module_name}_set_mode(motor_mode_t mode) {{
    ESP_LOGI(TAG, "Setting motor mode to %d", mode);
    s_motor_mode = mode;
    return ESP_OK;
}}

esp_err_t {module_name}_set_torque(float torque) {{
    if (s_motor_state != MOTOR_STATE_ENABLED) {{
        return ESP_ERR_INVALID_STATE;
    }}
    ESP_LOGI(TAG, "Setting torque to %f", torque);
    return ESP_OK;
}}

esp_err_t {module_name}_set_velocity(float velocity) {{
    if (s_motor_state != MOTOR_STATE_ENABLED) {{
        return ESP_ERR_INVALID_STATE;
    }}
    ESP_LOGI(TAG, "Setting velocity to %f", velocity);
    return ESP_OK;
}}

esp_err_t {module_name}_set_position(float position) {{
    if (s_motor_state != MOTOR_STATE_ENABLED) {{
        return ESP_ERR_INVALID_STATE;
    }}
    ESP_LOGI(TAG, "Setting position to %f", position);
    return ESP_OK;
}}

motor_state_t {module_name}_get_state(void) {{
    return s_motor_state;
}}

esp_err_t {module_name}_init(void) {{
    if (s_initialized) {{
        return ESP_OK;
    }}
    
    ESP_LOGI(TAG, "Initializing {module_name}");
    s_motor_state = MOTOR_STATE_READY;
    s_initialized = true;
    return ESP_OK;
}}

void {module_name}_cleanup(void) {{
    s_motor_state = MOTOR_STATE_DISABLED;
    s_initialized = false;
}}

'''
        
        # Add display implementation
        if is_display:
            source_content += f'''/* Display Implementation */
#include "lvgl.h"

lv_disp_t *s_disp = NULL;
lv_indev_t *s_indev = NULL;

esp_err_t {module_name}_display_init(void) {{
    ESP_LOGI(TAG, "Initializing LVGL display");
    /* LVGL initialization would go here */
    s_initialized = true;
    return ESP_OK;
}}

esp_err_t {module_name}_display_clear(void) {{
    lv_scr_load(lv_disp_get_scr_act(s_disp));
    return ESP_OK;
}}

esp_err_t {module_name}_display_text(const char *text, int x, int y) {{
    lv_label_t *label = lv_label_create(lv_scr_act());
    lv_label_set_text(label, text);
    lv_obj_set_pos(label, x, y);
    return ESP_OK;
}}

esp_err_t {module_name}_display_update(void) {{
    lv_refr_now(s_disp);
    return ESP_OK;
}}

'''
        
        # Default implementation if no specific modules detected
        if not (is_can or is_ble or is_motor or is_display):
            source_content += f'''/* Default Implementation */
esp_err_t {module_name}_init(void) {{
    if (s_initialized) {{
        return ESP_OK;
    }}
    
    ESP_LOGI(TAG, "Initializing {module_name}");
    s_initialized = true;
    return ESP_OK;
}}

void {module_name}_cleanup(void) {{
    s_initialized = false;
}}

bool {module_name}_is_initialized(void) {{
    return s_initialized;
}}

'''
        else:
            # Add is_initialized for modules with specific implementations
            source_content += f'''
bool {module_name}_is_initialized(void) {{
    return s_initialized;
}}

'''
        
        # Write files
        include_dir = self.workspace / 'include'
        include_dir.mkdir(parents=True, exist_ok=True)
        header_path = include_dir / f'{module_name}.h'
        code_files.append(CodeFile(path=str(header_path), content=header_content, language='c'))
        
        src_dir = self.workspace / 'src'
        src_dir.mkdir(parents=True, exist_ok=True)
        source_path = src_dir / f'{module_name}.c'
        code_files.append(CodeFile(path=str(source_path), content=source_content, language='c'))
        
        return code_files
    
    def run_tests(self, code_dir: Path) -> TestResult:
        """Run tests using ESP-IDF or fallback to gcc."""
        import time
        start_time = time.time()
        
        idf_path = Path('/opt/esp-idf')
        
        # Try ESP-IDF first
        if idf_path.exists():
            try:
                # Run ESP-IDF host tests
                cmd = ['idf.py', '-B', 'build-host', 'build-test']
                result = subprocess.run(cmd, cwd=code_dir, capture_output=True, text=True, timeout=180)
                
                if result.returncode == 0:
                    # Run the host test
                    test_exe = code_dir / 'build-host' / 'host_test' / 'test_runner'
                    if test_exe.exists():
                        run_result = subprocess.run([str(test_exe)], capture_output=True, text=True, timeout=30)
                        return TestResult(
                            passed=run_result.returncode == 0,
                            output=run_result.stdout + run_result.stderr,
                            errors=[] if run_result.returncode == 0 else [run_result.stderr],
                            duration_ms=int((time.time() - start_time) * 1000)
                        )
                
                return TestResult(
                    passed=False,
                    output=result.stdout + result.stderr,
                    errors=[result.stderr],
                    duration_ms=int((time.time() - start_time) * 1000)
                )
            except Exception as e:
                print(f"[C_HANDLER] ESP-IDF test failed, trying gcc fallback: {e}")
        
        # GCC fallback for syntax checking
        return self._gcc_syntax_check(code_dir, start_time)
    
    def _gcc_syntax_check(self, code_dir: Path, start_time: float) -> TestResult:
        """Fallback to gcc syntax checking."""
        import time
        
        test_files = list(code_dir.glob('test/test_*.c'))
        src_files = list(code_dir.glob('src/*.c'))
        include_files = list(code_dir.glob('include/*.h'))
        
        if not test_files:
            return TestResult(
                passed=False,
                output="No test files found",
                errors=["No test files in test/ directory"],
                duration_ms=int((time.time() - start_time) * 1000)
            )
        
        # Create minimal Unity stub for syntax check
        unity_stub = '''
#ifndef UNITY_H
#define UNITY_H
#define TEST_ASSERT_TRUE(x) do { if (!(x)) return 1; } while(0)
#define UNITY_BEGIN() (0)
#define UNITY_END() (0)
#define RUN_TEST(test) do { test(); } while(0)
#endif
'''
        unity_path = code_dir / 'test' / 'unity.h'
        unity_path.parent.mkdir(parents=True, exist_ok=True)
        with open(unity_path, 'w') as f:
            f.write(unity_stub)
        
        test_file = test_files[0]
        output_exe = code_dir / 'test_runner'
        
        cmd = ['gcc', '-I' + str(code_dir / 'test'), '-I' + str(code_dir / 'include'), 
               '-I' + str(code_dir / 'src'), '-DIDF_TARGET=host', '-Wall', '-Wextra',
               str(test_file)]
        
        for src in src_files:
            cmd.append(str(src))
        
        cmd.extend(['-o', str(output_exe)])
        
        try:
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
            
            if result.returncode != 0:
                return TestResult(
                    passed=False,
                    output=result.stdout + result.stderr,
                    errors=[result.stderr],
                    duration_ms=int((time.time() - start_time) * 1000)
                )
            
            run_result = subprocess.run([str(output_exe)], capture_output=True, text=True, timeout=30)
            return TestResult(
                passed=run_result.returncode == 0,
                output=run_result.stdout + run_result.stderr,
                errors=[] if run_result.returncode == 0 else [run_result.stderr],
                duration_ms=int((time.time() - start_time) * 1000)
            )
        except Exception as e:
            return TestResult(
                passed=False,
                output=str(e),
                errors=[str(e)],
                duration_ms=int((time.time() - start_time) * 1000)
            )
